//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class DichVuSuDung
    {
        public string MaHDDV { get; set; }
        public string MaDV { get; set; }
        public int SoLuongDV { get; set; }
        public Nullable<System.DateTime> NgaySD { get; set; }
    
        public virtual DichVu DichVu { get; set; }
        public virtual HoaDonDV HoaDonDV { get; set; }
    }
}
