//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonTT
    {
        public string MaHDTT { get; set; }
        public string MaPT { get; set; }
        public string MaNV { get; set; }
        public System.DateTime NgayLap { get; set; }
        public Nullable<int> Tongtiendv { get; set; }
        public Nullable<int> Tongtienpt { get; set; }
        public string GhiChu { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        public virtual PhieuThue PhieuThue { get; set; }
    }
}
