//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuThue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuThue()
        {
            this.HoaDonDVs = new HashSet<HoaDonDV>();
            this.HoaDonTTs = new HashSet<HoaDonTT>();
            this.PhongTTs = new HashSet<PhongTT>();
            this.PhongTTs1 = new HashSet<PhongTT>();
        }
    
        public string MaPT { get; set; }
        public string MaKH { get; set; }
        public string MaNV { get; set; }
        public System.DateTime NgaylapP { get; set; }
        public System.DateTime NgaythueP { get; set; }
        public Nullable<System.DateTime> Ngayhentr { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<int> TienDatCoc { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonDV> HoaDonDVs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonTT> HoaDonTTs { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhongTT> PhongTTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhongTT> PhongTTs1 { get; set; }
    }
}
