//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhongTT
    {
        public string MaPT { get; set; }
        public string MaPhong { get; set; }
        public Nullable<System.DateTime> NgayTraP { get; set; }
        public Nullable<int> ThanhTien { get; set; }
    
        public virtual PhongKS PhongK { get; set; }
        public virtual PhongKS PhongK1 { get; set; }
        public virtual PhieuThue PhieuThue { get; set; }
        public virtual PhieuThue PhieuThue1 { get; set; }
    }
}
